-- Reference taxonomy only. This file contains no users, listings, offers, or messages.
insert into public.locations(slug,name,group_name) values
('pg-potheri','PG Potheri','Nearby PG / off-campus'),('pg-trs','PG TRS','Nearby PG / off-campus'),('estancia','Estancia','Nearby PG / off-campus'),('abode','Abode','Nearby PG / off-campus'),
('paari','Paari','Hostel for Men'),('kaari','Kaari','Hostel for Men'),('oori','Oori','Hostel for Men'),('adhiyaman','Adhiyaman','Hostel for Men'),('nelson-mandela','Nelson Mandela','Hostel for Men'),('sannasi-a','Sannasi A','Hostel for Men'),('manoranjitham','Manoranjitham','Hostel for Men'),('began','Began','Hostel for Men'),('n-block-premium','N Block (Premium)','Hostel for Men'),('agasthiyar','Agasthiyar','Hostel for Men'),('pierre-fauchard','Pierre Fauchard','Hostel for Men'),('ja-block-2','JA Block 2 (Off-Campus)','Hostel for Men'),
('kalpana-chawla','Kalpana Chawla','Hostel for Women'),('meenakshi','Meenakshi','Hostel for Women'),('m-block','M Block','Hostel for Women'),('malligai','Malligai','Hostel for Women'),('thamarai','Thamarai','Hostel for Women'),('mullai','Mullai','Hostel for Women'),('shenbagam','Shenbagam','Hostel for Women'),('sannasi-c','Sannasi C','Hostel for Women'),('esq-a-b','ESQ – A & B','Hostel for Women'),
('nri-premium-international','NRI Premium International Hostel','Co-ed / international formats'),('green-pearl-international','Green Pearl International Hostel','Co-ed / international formats')
on conflict (slug) do update set name=excluded.name,group_name=excluded.group_name;

insert into public.categories(slug,name,feature_flag) values
('room-essentials','Room essentials',null),('furniture-storage','Furniture and storage',null),('bedding','Bedding',null),('kitchen-cooking','Kitchen and cooking',null),('study-books','Study supplies and books',null),('electronics','Electronics',null),('mobile-computer-accessories','Mobile and computer accessories',null),('cycles-mobility','Cycles and mobility',null),('fitness-sports','Fitness and sports',null),('clothing-accessories','Clothing and accessories',null),('decor-lighting','Decor and lighting',null),('appliances-cooling','Appliances and cooling',null),('sealed-packaged-food','Sealed packaged food',null),('free-giveaway','Free / giveaway',null),('services-skill-swaps','Services and skill swaps','services_skill_swaps'),('other','Other',null)
on conflict (slug) do update set name=excluded.name,feature_flag=excluded.feature_flag;
